package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

var signatureRE = regexp.MustCompile(`^\s*([^\s]+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*\((.*)\)\s*$`)

var scalarTypes = map[string]string{
	"boolean": "bool",
	"int":     "int64",
	"float":   "float64",
	"string":  "string",
}

var enumTypes = map[string]string{
	"item": "Item", "familiar": "Familiar", "skill": "Skill", "effect": "Effect",
	"monster": "Monster", "location": "Location", "slot": "Slot", "stat": "Stat",
	"path": "Path", "class": "AscensionClass", "element": "Element", "phylum": "Phylum",
	"thrall": "Thrall", "servant": "Servant", "coinmaster": "Coinmaster",
}

type sig struct {
	Ret, Name string
	Args      []string
}

func main() {
	in := flag.String("in", "", "ashref output file")
	out := flag.String("out", "generated_ash.go", "output Go file")
	pkg := flag.String("package", "ash", "Go package name")
	flag.Parse()
	if *in == "" {
		fatal("-in is required")
	}

	f, err := os.Open(*in)
	if err != nil {
		fatal(err.Error())
	}
	defer f.Close()

	seen := map[string]bool{}
	var supported []sig
	var skipped []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		m := signatureRE.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		s := sig{Ret: strings.ToLower(m[1]), Name: m[2]}
		if strings.TrimSpace(m[3]) != "" {
			parts := strings.Split(m[3], ",")
			for _, p := range parts {
				s.Args = append(s.Args, strings.ToLower(strings.TrimSpace(p)))
			}
		}
		if seen[s.Name] {
			skipped = append(skipped, line+" // overloaded name")
			continue
		}
		if _, ok := scalarTypes[s.Ret]; !ok {
			skipped = append(skipped, line+" // unsupported return type")
			continue
		}
		ok := true
		for _, arg := range s.Args {
			if _, scalar := scalarTypes[arg]; scalar {
				continue
			}
			if _, enum := enumTypes[arg]; enum {
				continue
			}
			ok = false
		}
		if !ok {
			skipped = append(skipped, line+" // unsupported argument type")
			continue
		}
		seen[s.Name] = true
		supported = append(supported, s)
	}
	if err := scanner.Err(); err != nil {
		fatal(err.Error())
	}
	sort.Slice(supported, func(i, j int) bool { return supported[i].Name < supported[j].Name })

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by ashrefgen; DO NOT EDIT.\npackage %s\n\nimport \"context\"\n\n", *pkg)
	for _, s := range supported {
		method := pascal(s.Name)
		js := camel(s.Name)
		ret := scalarTypes[s.Ret]
		params := []string{"ctx context.Context"}
		callArgs := []string{}
		for i, arg := range s.Args {
			goType := scalarTypes[arg]
			if goType == "" {
				goType = enumTypes[arg]
			}
			name := fmt.Sprintf("arg%d", i+1)
			params = append(params, name+" "+goType)
			callArgs = append(callArgs, name)
		}
		fmt.Fprintf(&b, "func (c *Client) %s(ctx context.Context", method)
		if len(params) > 1 {
			fmt.Fprintf(&b, ", %s", strings.Join(params[1:], ", "))
		}
		fmt.Fprintf(&b, ") (%s, error) {\n", ret)
		fmt.Fprintf(&b, "\tv, err := c.Call(ctx, %q", js)
		if len(callArgs) > 0 {
			fmt.Fprintf(&b, ", %s", strings.Join(callArgs, ", "))
		}
		fmt.Fprintf(&b, ")\n\tif err != nil { var zero %s; return zero, err }\n", ret)
		switch ret {
		case "string":
			fmt.Fprintf(&b, "\treturn v.String()\n")
		case "int64":
			fmt.Fprintf(&b, "\treturn v.Int64()\n")
		case "float64":
			fmt.Fprintf(&b, "\treturn v.Float64()\n")
		case "bool":
			fmt.Fprintf(&b, "\treturn v.Bool()\n")
		}
		fmt.Fprintf(&b, "}\n\n")
	}
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fatal("format generated source: " + err.Error())
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fatal(err.Error())
	}
	fmt.Fprintf(os.Stderr, "generated=%d skipped=%d output=%s\n", len(supported), len(skipped), *out)
	for _, line := range skipped {
		fmt.Fprintln(os.Stderr, "skip:", line)
	}
}

func camel(s string) string {
	p := pascal(s)
	if p == "" {
		return ""
	}
	r := []rune(p)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

func pascal(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == ' ' })
	for i, p := range parts {
		if p == "" {
			continue
		}
		r := []rune(p)
		r[0] = unicode.ToUpper(r[0])
		parts[i] = string(r)
	}
	return strings.Join(parts, "")
}

func fatal(msg string) { fmt.Fprintln(os.Stderr, "ashrefgen:", msg); os.Exit(1) }
